feat(shell): add dependency checks
Added session-based dependency detection and checks for TTS engine, xsel, and wl-clipboard.

diff --git a/shell/picotts b/shell/picotts
--- a/shell/picotts
+++ b/shell/picotts
@@ -2,24 +2,43 @@
 
 #########################################################
 # Script:       picotts                                 #
-# Version:      0.1                                     #
+# Version:      0.2                                     #
 # Author:       Adeel Ahmad (codegenki)                 #
 # Date Created: Feb 9, 2021                             #
-# Date Mod.:    Feb 9, 2021                             #
+# Date Mod.:    Dec 8, 2025                             #
 # Usage:        picotts                                 #
 # Description:  Script to play TTS for some text        #
 #########################################################
 
+APP_NAME=$(basename $0)
+
+# check availability of TTS engine
+_talk=`command -v pico2wave`
+if [ -z "$_talk" ]; then
+  echo "Missing dependency: install SVOX Pico engine!" >&2
+  exit 1
+fi
+
+# detect & decide audio player
+_player1=`command -v ffplay`
+_player2=`command -v aplay`
+if [ -z "$_player1" -a -z "$_player2" ]; then
+  echo "Missing dependency: install either of [alsa-utils, ffmpeg]" >&2
+  exit 1
+fi
+[ -n "$_player1" ] && _play="$_player1 -hide_banner -nodisp -autoexit"
+[ -z "$_play" ] && _play="$_player2 -q"
+
 # help msg
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-  echo "Usage: picotts <lang> <msg>"
+  echo "Usage: $APP_NAME <lang> <msg>"
   echo "Langs: en-US, en-GB, es-ES, de-DE, fr-FR, it-IT"
   exit 0
 fi
 
 # error: not enough arguments
 if [ $# -lt 2 ]; then
-  echo "picotts: not enough arguments were given" >&2
+  echo "$APP_NAME: not enough arguments" >&2
   exit 1
 fi
 
@@ -28,7 +47,7 @@ case "$1" in
   en-US|en-GB|es-ES|de-DE|fr-FR|it-IT)
     ;;
   *)
-    echo "picotts: unsupported language: $1" >&2
+    echo "$APP_NAME: unsupported language: $1" >&2
     exit 1
     ;;
 esac
@@ -43,8 +62,8 @@ lang_pico=$1
 shift
 
 # play message
-pico2wave -l $lang_pico -w "$tmpfilewav" "$*"
-aplay -q "$tmpfilewav"
+$_talk -l $lang_pico -w "$tmpfilewav" "$*"
+$_play "$tmpfilewav" 2>/dev/null
 
 # delete temp file
 rm "$tmpfilewav"
diff --git a/shell/picotts-sel b/shell/picotts-sel
--- a/shell/picotts-sel
+++ b/shell/picotts-sel
@@ -2,17 +2,31 @@
 
 #########################################################
 # Script:       picotts-sel                             #
-# Version:      0.1                                     #
+# Version:      0.2                                     #
 # Author:       Adeel Ahmad (codegenki)                 #
 # Date Created: Feb 9, 2021                             #
-# Date Mod.:    Feb 9, 2021                             #
+# Date Mod.:    Dec 8, 2025                             #
 # Usage:        picotts-sel                             #
 # Description:  Script to play TTS for selected text    #
 #########################################################
 
+APP_NAME=$(basename $0)
+
+# detect & decide selector application
+_selector=
+if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
+  [ -n $(command -v wl-paste) ] \
+    && _selector="wl-paste --primary --no-newline" \
+    || { echo "wl-paste required in wayland session! Install wl-clipboard."; return 1; }
+elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
+  [ -n $(command -v xsel) ] \
+    && _selector="xsel -o" \
+    || { echo "xsel required in x11 session! Install xsel."; return 1; }
+fi
+
 # help message
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-  echo "Usage: picotts-sel"
+  echo "Usage: $APP_NAME"
   echo "Language will be automatically detected from system locale"
   echo "Supported languages: English, Spanish, German, French and Italian"
   exit 0
@@ -52,19 +66,19 @@ if [ "$#" -eq 0 ]; then
       lang_pico="it-IT"
       ;;
     *)
-      echo "picotts-sel: unsupported language: $lang" >&2
+      echo "$APP_NAME: unsupported language: $lang" >&2
       exit 1
       ;;
   esac
 
-  # get selection from X server
-  sayit=$(xsel -o)
+  # get selection from X server/wayland
+  sayit=$(eval $_selector)
   if [ -n "$sayit" ]; then
     # play selection text
     picotts $lang_pico $sayit
   else
     # error: no text selected
-    echo "picotts-sel: no text selected, select some text before invoking."  >&2
+    echo "$APP_NAME: no text selected, select some text before invoking."  >&2
     exit 1
   fi
 fi
